version: '3.9'
services:
  redis:
    image: 'redis:latest'
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass 123123
    volumes:
      - ./Redis/redis.conf:/usr/local/etc/redis/redis.conf
    
    environment:
     - REDIS_REPLICATION_MODE=master